export * from './MainPage/MainPage'
export * from './AddPostPage/AddPostPage'
export * from './EditPostPage/EditPostPage'
export * from './LoginPage/LoginPage'
export * from './PostPage/PostPage'
export * from './PostsPage/PostsPage'
export * from './RegisterPage/RegisterPage'
